### ISSUE TITLE
关于知乎上的一条评论

### ISSUE THREAD

**Issue by karlmaxtan** [vanshady/esuds#1]
先生您好，十分冒昧，想请求您帮忙删除一条知乎上的评论，我几年前评论过一次您的知乎回答，但当时的账号注销了，因为这条评论里有我的个人信息，所以想请求您帮忙删除一下，实在联系不到您才想到用这个渠道，如果可以的话，万分感谢
![20ddb2d6eefef596372e638e4701638](https://github.com/vanshady/esuds/assets/166829728/068a289f-1676-4907-bedb-feb2d278d19e)
![e17e2a0d1d443463b66115cadfd8aeb](https://github.com/vanshady/esuds/assets/166829728/df0104a4-b41e-43ce-9436-3a30e2ddf033)

**Comment by vanshady** [comment]
不好意思我也没有知乎账号access了

**Comment by karlmaxtan** [comment]
好吧，谢谢
